-- NAME:...
-- ID:...
-- SE2222 LAB PRACTICE (23.03.2020) 
-- USE THIS SQL FILE AS TEMPLATE. 
-- FOR EACH QUESTION, WRITE ONE SQL STATEMENT. 
-- IF YOU ARE ASKED TO EXPLAIN A QUERY, WRITE COMMENT LINE FOR EXPLANATION. 
-- SUBMIT YOUR FILES LIKE [YOURID].SQL
-- YOUR SUBMITTED FILE MUST BEGIN WITH COMMENT LINES CONTAINING YOUR NAME AND ID.
-- OTHERWISE WILL NOT BE EVALUATED.
-- 
-- ______________________________________________________________________________
-- 1. DEFINE TABLE AUTHORS WITH COLUMNS AUTHORID INT AND AUTHORNAME VARCHAR(30) 
-- ADD COLUMN LEVEL PRIMARY KEY CONSTRAINT FOR AUTHORID
-- ADD COLUMN LEVEL NOT NULL CONSTRAINT FOR AUTHORNAME 
CREATE TABLE AUTHORS(
	AUTHORID INT PRIMARY KEY,
	AUTHORNAME VARCHAR(30) NOT NULL		
);
-- 2. INSERT SOME VALUES TO AUTHORS TABLE
-- ID:3 AUTHOR:ILBER ORTAYLI
INSERT INTO AUTHORS VALUES(3,'İLBER ORTAYLI');
-- 3. ID:4 AUTHOR:JULES VERNE
INSERT INTO AUTHORS(AUTHORNAME, AUTHORID) VALUES ('JULES VERNE',4);
-- 4. DOES NEXT QUERY EXECUTE IF NOT WHY
INSERT INTO AUTHORS(AUTHORNAME) VALUES('STEPHEN HAWKING');
-- ...DEFALT VALUE FOR ID IS NOT DEFINED AND SINCE ITS PRIMARY KEY NULL IS NOT ACCEPTED

-- 5. DOES NEXT QUERY EXECUTE IF NOT WHY. EXPLAIN.
INSERT INTO AUTHORS VALUES(3,'STEPHEN HAWKING');
-- ...ID 3 IS ALREADY GIVEN FOR ANOTHER RECORD

-- 6. TRY ID:5 AUTHOR:STEPHEN HAWKING
INSERT INTO AUTHORS VALUES(5,'STEPHEN HAWKING');
-- 7. ID:6 AUTHOR:GEORGE ORWELL
INSERT INTO AUTHORS VALUES(6,'GEORGE ORWELL');
-- LETS CHECK OUR TABLE
SELECT * FROM AUTHORS;

-- 8. DEFINE TABLE PUBLISHERS WITH COLUMNS 
-- PUBLISHERID INT AND PUBLISHERNAME VARCHAR(30)
-- ADD TABLE LEVEL PRIMARY KEY CONSTRAINT FOR PUBLISHERID
-- ADD TABLE LEVEL UNIQUE CONSTRAINT FOR PUBLISHERNAME
CREATE TABLE PUBLISHERS(
	PUBLISHERID INT,
	PUBLISHERNAME VARCHAR(30),
	CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUBLISHERID),
	CONSTRAINT PUBLISHERNAME_UQ UNIQUE (PUBLISHERNAME)
);
-- 9. INSERT SOME VALUES TO PUBLISHERS TABLE
-- INSERT ID:1 NAME:ALFA YAYINCILIK
INSERT INTO PUBLISHERS VALUES(1,'ALFA YAYINCILIK');
-- 10. INSERT ID:2 NAME:KRONIK KITAP
INSERT INTO PUBLISHERS VALUES(2,'KRONIK KITAP');
-- 11. DOES NEXT QUERY EXECUTE IF NOT WHY. EXPLAIN.
INSERT INTO PUBLISHERS VALUES(3,'KRONIK KITAP');
-- ...PUBLISHERNAME MUST BE UNIQUE

-- 12. INSERT ID:3 NAME:CAN YAYINLARI
INSERT INTO PUBLISHERS VALUES(3,'CAN YAYINLARI');
-- 13. ADD NEW COLUMN CITY VARCHAR(20) FOR PUBLISHERS TABLE
ALTER TABLE PUBLISHERS ADD CITY VARCHAR(20);
-- 14. SET CITY OF PUBLISHER CAN YAYINLARI TO İSTANBUL
UPDATE PUBLISHERS SET CITY='İSTANBUL' WHERE PUBLISHERNAME='CAN YAYINLARI';
-- 15. WHAT IF WHERE CLAUSE IS FORGOTTEN. EXPLAIN
UPDATE PUBLISHERS SET CITY='İSTANBUL';
SELECT * FROM PUBLISHERS;
-- ...CITY OF ALL RECORDS SET AS İSTANBUL

-- 16. DEFINE TABLE NAMED BOOKS WITH COLUMNS 
-- BOOKID INT, TITLE VARCHAR(30), AUTHORID ?, PUBLISHERID ?, 
-- GENRE VARCHAR(20)
-- ADD FOREIGN KEY CONSTRAINT PUBLISHERID
-- ADD FOREIGN KEY CONSTRAINT AUTHORID WITH ON DELETE CASCADE
-- ON DELETE CASCADE (WHEN A REFERENCED PARENT TABLE ROW IS REMOVED 
-- ALL THE CHILD ARE REMOVED AUTOMATICALLY) 
CREATE TABLE BOOKS(
	BOOKID INT NOT NULL,
	TITLE VARCHAR(30) NOT NULL,
	AUTHORID INT,
	PUBLISHERID INT,
	GENRE VARCHAR(20),
	CONSTRAINT BOOK_PUBLISHER_FK FOREIGN KEY (PUBLISHERID) REFERENCES PUBLISHERS (PUBLISHERID),
	CONSTRAINT BOOK_AUTHOR_FK FOREIGN KEY (AUTHORID) REFERENCES AUTHORS (AUTHORID) ON DELETE CASCADE
);
-- 17. ALTER TABLE BOOKS AND ADD NEW PRIMARY KEY CONSTRAINT FOR BOOKID
ALTER TABLE BOOKS ADD CONSTRAINT BOOK_PK PRIMARY KEY (BOOKID);
-- 18. ADD NEW COLUMN PRIZE NUMERIC(5,2) FOR BOOKS TABLE
ALTER TABLE BOOKS ADD PRIZE NUMERIC(5,2);
-- 19. ALTER TABLE BOOKS AND ADD NEW CHECK CONSTRAINT FOR PRIZE>=5.00
ALTER TABLE BOOKS ADD CONSTRAINT PRIZE_CK CHECK (PRIZE>=5.00);
-- 20. INSERT SOME VALUES TO BOOKS TABLE
-- INSERT ID:1,TITLE:HAYVAN ÇİFTLİĞİ,AUTHOR:GEORGE ORWELL , 
-- PUBLISHER:CAN YAYINLARI, GENRE:SCIENCE FICTION,PRIZE=10.00
INSERT INTO BOOKS VALUES(1,'HAYVAN ÇİFTLİĞİ',6,3,'SCIENCE FICTION',10.00);
-- 21. INSERT ID:2,TITLE:KARA DELİKLER, AUTHORID:5, PUBLISHERID:1 
-- WE DONT KNOW GENRE AND PRIZE
INSERT INTO BOOKS(BOOKID,TITLE,AUTHORID,PUBLISHERID) VALUES(2,'KARA DELİKLER',5,1);
-- 22. DOES NEXT QUERY WORK IF NOT WHY. EXPLAIN.
INSERT INTO BOOKS VALUES(3,'GAZİ MUSTAFA KEMAL ATATÜRK',3,2,'BIOGRAPHY',4.00);
-- ...PRIZE_CK CONSTRAINT DOES NOT ALLOW INSERTIONS WHERE PRIZE IS LOWER THAN 5.00
-- 23. INSERT SAME ABOVE WITH PRIZE 15.00
INSERT INTO BOOKS VALUES(3,'GAZİ MUSTAFA KEMAL ATATÜRK',3,2,'BIOGRAPHY',15.00);
-- 24. INSERT ID:4,TITLE:ZAMANIN KISA TARİHİ,AUTHORID:5, PUBLISHERID:1,
-- GENRE:POPULAR SCIENCE,PRIZE:10.00
INSERT INTO BOOKS VALUES(4,'ZAMANIN KISA TARİHİ',5,1,'POPULAR SCIENCE',10.00);
-- 25. ADD NEW COLUMN NATION CHAR(2) FOR AUTHORS TABLE
ALTER TABLE AUTHORS ADD NATION CHAR(2);
-- 26. UPDATE AUTHOR NATIONALITIES 
-- TR,FR AND EN FOR RELATED AUTHORS
UPDATE AUTHORS SET NATION='TR' WHERE AUTHORID=3;
UPDATE AUTHORS SET NATION='FR' WHERE AUTHORID=4;
UPDATE AUTHORS SET NATION='EN' WHERE AUTHORID=6;
UPDATE AUTHORS SET NATION='EN' WHERE AUTHORID=5;
-- 27. DELETE PUBLISHER 'CAN YAYINLARI'
-- IS IT POSSIBLE. EXPLAIN.
DELETE FROM PUBLISHERS WHERE PUBLISHERNAME='CAN YAYINLARI';
-- ...PUBLISHERID IS FOREIGN KEY AND THERE ARE BOOK RECORDS WHERE PUBLISHER ID IS 3 (CAN YAYINLARI)

-- 28. DELETE AUTHOR 'GEORGE ORWELL'
-- IS IT POSSIBLE. EXPLAIN.
DELETE FROM AUTHORS WHERE AUTHORNAME='GEORGE ORWELL'
-- ...YES BUT RELATED BOOKS ARE ALSO DELETED
-- 29. LETS CHECK EFFECTS ON OTHER TABLES
SELECT * FROM BOOKS
SELECT * FROM PUBLISHERS
SELECT * FROM AUTHORS
-- EXPLAIN
-- ...

