-- NAME:Efe Can Nerman...
-- ID:17070006023...
-- SE2222 LAB PRACTICE (30.03.2020) 
-- USE THIS SQL FILE AS TEMPLATE. 
-- FOR EACH QUESTION, WRITE ONE SQL STATEMENT. 
-- IF YOU ARE ASKED TO EXPLAIN A QUERY, WRITE COMMENT LINE FOR EXPLANATION. 
-- SUBMIT YOUR FILES LIKE [YOURID].SQL
-- YOUR SUBMITTED FILE MUST BEGIN WITH COMMENT LINES CONTAINING YOUR NAME AND ID.
-- OTHERWISE WILL NOT BE EVALUATED.
-- BEFORE BEGINNING RUN DEMO.SQL AS WE HAVE DONE IN THE LAB
-- ______________________________________________________________________________
-- 1. ADD ALL EMPLOYEES TO BONUS TABLE
INSERT INTO BONUS(ENAME,JOB,SAL,COMM)
SELECT emp.ENAME,emp.JOB,emp.SAL,emp.COMM
FROM emp;


-- CHECK
SELECT * FROM BONUS;

-- 2. CREATE A VIEW EMP2(EMPNO, ENAME, JOB, DEPTNO)
CREATE VIEW EMP2 AS
SELECT EMPNO,ENAME,JOB,DEPTNO
FROM emp;

-- CHECK
SELECT * FROM EMP2;

-- 3. TRY TO ADD NEW EMPLOYEE TO EMP2
-- 1111, 'EMP1', 'CLERK', 10
INSERT INTO EMP2
VALUES(1111,'EMP1','CLERK',10);
-- WAS THE RECORD ADDED TO EMP?
-- CHECK --	Can not modify emp2 beacuse it is a view
SELECT * FROM EMP2;
SELECT * FROM EMP;

-- 4. CREATE A VIEW EMPDEPT(EMPNO, ENAME, JOB, DNAME)

CREATE VIEW EMPDEPT AS
SELECT EMPNO,ENAME,JOB,DNAME
FROM emp,dept
WHERE emp.deptno=dept.deptno;

-- CHECK
 SELECT * FROM EMPDEPT;

-- 5. TRY TO ADD NEW EMPLOYEE TO EMPDEPTbonus
-- 2222, 'EMP2', 'CLERK', 'SALES'
 INSERT INTO EMPDEPT
VALUES(2222,'EMP2','CLERK','SALES');

-- IF CANNOT EXPLAIN...this process unsuccessfull because view do not accept the insertion 

-- 6. CREATE A VIEW EMPDEPTSAL(EMPNO, ENAME, JOB, DNAME, GRADE)
-- GRADE IS SALARY GRADE OF EMPLOYEE
CREATE VIEW EMPDEPTSAL AS
SELECT emp.EMPNO,emp.ENAME,emp.JOB,dept.DNAME,salgrade.GRADE
FROM emp,dept,salgrade
where emp.DEPTNO = dept.DEPTNO AND emp.SAL BETWEEN salgrade.LOSAL AND salgrade.HISAL;
 
-- CHECK
SELECT  * FROM EMPDEPTSAL;

-- 7. TRY TO ADD NEW EMPLOYEE TO EMPDEPTSAL
-- 3333, 'EMP3', 'CLERK', 'SALES',1
INSERT INTO EMPDEPTSAL
VALUES(3333,'EMP3','CLERK','SALES',1);
-- IF CANNOT EXPLAIN...I CANNOT INSERT LIKE ABOVE EXAMPLE

-- 8. CREATE A VIEW EMPMGR(EMPNO, ENAME, MGRNAME)
-- MGRNAME IS THE NAME OF EMPLOYEE'S MANAGER
CREATE VIEW  EMPMGR AS
SELECT emp.EMPNO,emp.ENAME,(SELECT ENAME FROM emp WHERE emp.MGR=emp.EMPNO) MANAGER
FROM emp;

-- CHECK
SELECT * FROM EMPMGR;

-- 9. TRY TO ADD NEW EMPLOYEE TO EMPMGR
-- 4444, 'EMP4', 'KING'
INSERT INTO EMPMGR
VALUES(4444,'EMP4','KING');
-- IF CANNOT EXPLAIN...

-- 10. CREATE A VIEW JOBS(JOB, NUMBEROFEMPLOYEES)
-- NUMBEROFEMPLOYEES STORES  NUMBER OF EMPLOYEES FOR EACH JOB
CREATE VIEW JOBS AS
SELECT count(job) 
from emp
group by job;
-- CHECK
SELECT * FROM JOBS;

-- 11. TRY TO ADD NEW JOB TO JOBS
-- 'INTERN', 6
INSERT INTO JOBS
VALUES('INTERN',6);
-- IF CANNOT DO SUCH OPERATION
-- EXPLAIN DRAWBACKS IF WE COULD INSERT SUCH RECORD TO JOBS VIEW
-- .this state does not work because of groupby ..

-- 12. IS THERE A WAY TO INSERT RECORDS TO JOINED VIEWS
-- SHORTLY EXPLAIN HOW
-- .Modify the view and then insert ..
-- We must add ıntern to base table and then modify the view and lastly insertion
-- 13. CREATE A VIEW MANAGERS(EMPNO, ENAME, JOB)
-- FOR EMPLOYEES WHO ARE MANAGER
CREATE VIEW MANAGERS AS
SELECT emp.EMPNO,emp.ENAME,emp.JOB
from emp E1,emp E2
where emp.MGR=emp.EMPNO;
 
-- CHECK
SELECT * FROM MANAGERS;
-- 14. INSERT A MANAGER TO MANAGERS 
-- 9999,'EMP9','MANAGER'
INSERT INTO MANAGERS
VALUES(9999,'EMP9','MANAGER');
-- IS IT POSSIBLE TO INSERT RECORD TO VIEWS
-- .YES..
-- DOES IT EFFECT BASE TABLE EMP
-- ...yes this data added base table emp 
-- CHECK
SELECT * FROM MANAGERS;
SELECT * FROM EMP;
-- 15. INSERT A CLERK TO MANAGERS VIEW
-- 8888,'EMP8','CLERK'
INSERT INTO MANAGERS
VALUES(8888,'EMP8','CLERK');
-- IS IT POSSIBLE
-- .yes it is possible..
-- CHECK
SELECT * FROM MANAGERS;
SELECT * FROM EMP;
-- 16. CREATE A VIEW CLERKS(EMPNO, ENAME, JOB) WITH CHECK OPTION
-- FOR EMPLOYEES WHO ARE CLERK
CREATE VIEW CLERKS AS
SELECT emp.EMPNO,emp.ENAME,emp.JOB
from emp
where job ='CLERK'
WITH CHECK OPTION;
-- CHECK
SELECT * FROM CLERKS;
-- 17. INSERT A CLERK TO CLERKS VIEW
-- 7777, 'EMP7','CLERK'
INSERT INTO CLERKS
VALUES(7777,'EMP7','CLERK');
-- CHECK
SELECT * FROM CLERKS;
SELECT * FROM EMP;
-- 18. INSERT A MANAGER TO CLERKS VIEW
-- 6666, 'EMP6','MANAGER'
INSERT INTO CLERKS
VALUES(6666,'EMP6','MANAGER');
-- IS IT POSSIBLE
-- no because  with check option does not permit this changes ...
-- CHECK
SELECT * FROM EMP;
SELECT * FROM CLERKS;